version: 2.1

jobs:
  build:
    docker:
      - image: rebble/pebble-sdk:latest
    steps:
      - checkout
      - run:
          name: Build Pebble app
          command: |
            pebble build
      - run:
          name: Archive build artifacts
          command: mkdir -p build_artifacts && cp release/urchin-cgm.pbw build_artifacts/ || true
      - store_artifacts:
          path: build_artifacts
          destination: build

workflows:
  build-and-deploy:
    jobs:
      - build
